#!/bin/bash
cd
rm -f key.*
os_version=$(lsb_release -sr);
distribution=$(lsb_release -si);
fun_a(){
texto=`if netstat -tunlp |grep apache2 1> /dev/null 2> /dev/null; then
echo -e "ON"
else
echo -e "OFF"
fi`;
if [[ $texto = "ON" ]];then
echo "Apache2 Instalado y Activo"
#sed -i "s;Listen 80;Listen 81;g" /etc/apache2/ports.conf
#service apache2 restart > /dev/null 2>&1
else
echo "Apache2 No Instalado"
echo -ne " \033[1;31m[ ! ] INSTALANDO APACHE2 "
apt-get install apache2 -y > /dev/null 2>&1 && echo -e "\033[1;32m [ EXITO ]" || echo -e "\033[1;31m [FAIL]"
sed -i "s;Listen 80;Listen 81;g" /etc/apache2/ports.conf
service apache2 restart > /dev/null 2>&1
fi
}
fun_ip () {
MEU_IP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
MEU_IP2=$(wget -qO- ipv4.icanhazip.com)
[[ "$MEU_IP" != "$MEU_IP2" ]] && echo "$MEU_IP2" || echo "$MEU_IP"
}
IP="$(fun_ip)"
declare -A cor=( [0]="\033[1;37m" [1]="\033[1;34m" [2]="\033[1;31m" [3]="\033[1;33m" [4]="\033[1;32m" )
barra="\033[0m\e[34m======================================================\033[1;37m"
#SCPfrm="/etc/ger-frm" && [[ ! -d ${SCPfrm} ]] && exit
#SCPinst="/etc/ger-inst" && [[ ! -d ${SCPinst} ]] && exit
#MENUS ONLINES
veronline(){
[[ -z $(ls /var/www/html) ]] && echo -e "$barra"  || {
    for my_arqs in `ls /var/www/html`; do
    [[ "$my_arqs" = "index.html" ]] && continue
    [[ "$my_arqs" = "index.php" ]] && continue
    [[ -d "$my_arqs" ]] && continue
    echo -e "\033[1;31m[$my_arqs] \033[1;36mhttp://$IP:81/$my_arqs\033[0m"
    done
    echo -e "$barra"
    }
}
removeonline(){
i=1
    [[ -d /var/www/html ]] && [[ -e /var/www/html/$arquivo_move ]] && rm -rf /var/www/html/$arquivo_move > /dev/null 2>&1
    [[ -e /var/www/$arquivo_move ]] && rm -rf /var/www/$arquivo_move > /dev/null 2>&1
    echo -e "${cor[5]}Key Exitosa"
    echo -e "$barra"
echo "SUBIENDO"
subironline
}   
subironline(){
[ ! -d /var ] && mkdir /var
[ ! -d /var/www ] && mkdir /var/www
[ ! -d /var/www/html ] && mkdir /var/www/html
[ ! -e /var/www/html/index.html ] && touch /var/www/html/index.html
[ ! -e /var/www/index.html ] && touch /var/www/index.html
chmod -R 755 /var/www
cp $HOME/$arquivo_move /var/www/$arquivo_move
cp $HOME/$arquivo_move /var/www/html/$arquivo_move
service apache2 restart
echo -e "\033[1;36m http://$IP:81/$arquivo_move\033[0m"
echo -e "$barra"
echo -e "${cor[5]}Key Exitosa!"
echo -e "$barra"
read -p "PRESIONE ENTER"
}

ofus () {
unset txtofus
number=$(expr length $1)
for((i=1; i<$number+1; i++)); do
txt[$i]=$(echo "$1" | cut -b $i)
case ${txt[$i]} in
".")txt[$i]="+";;
"+")txt[$i]=".";;
"1")txt[$i]="@";;
"@")txt[$i]="1";;
"2")txt[$i]="?";;
"?")txt[$i]="2";;
"4")txt[$i]="%";;
"%")txt[$i]="4";;
"-")txt[$i]="K";;
"K")txt[$i]="-";;
"m")txt[$i]="7";;
"7")txt[$i]="m";;
"S")txt[$i]="i";;
"i")txt[$i]="S";;
"C")txt[$i]="h";;
"h")txt[$i]="C";;
"f")txt[$i]="3";;
"3")txt[$i]="f";;
"5")txt[$i]="s";;
"s")txt[$i]="5";;
"0")txt[$i]="8";;
"8")txt[$i]="0";;
"=")txt[$i]="_";;
"_")txt[$i]="=";;
"B")txt[$i]="g";;
"g")txt[$i]="B";;
"A")txt[$i]="r";;
"r")txt[$i]="A";;
"R")txt[$i]="b";;
"b")txt[$i]="R";;
esac
txtofus+="${txt[$i]}"
done
echo "$txtofus" | rev
}
listbar () {
echo -e "\033[1;35m Keys Activas En Linea"
for testus in $(ls /etc/adm-cgh |sort |sed 's/.sh//g')
do
echo "$testus"
done
}
listbarr () {
echo -e "\033[1;35m Keys Activas En Linea"
for testus in $(ls /etc/adm-russ |sort |sed 's/.sh//g')
do
echo "$testus"
done
}
clear
fun_a
clear
echo -e "\033[1;32m [0] > Regresar / Salir"
echo -e "\033[1;32m [1] > GENERAR KEY EN ADM CHUMOGH"
echo -e "\033[1;32m [2] > GENERAR KEY EN ADM RUSS"
echo -e "\033[1;32m [3] > Retirar KEY EN ADM CHUMOGH"
echo -e "\033[1;32m [4] > Retirar KEY EN ADM RUSS"
echo -e "\033[1;32m [5] > DESTRUIR KEYS de ChumoGH & RUSS\033[1;35m (No Recomendado) "
echo -e "\033[1;32m [6] > Ver KEYS de ChumoGH \033[1;34m (Encriptada) "
echo -e "\033[1;32m [7] > Ver KEYS de RUSS \033[1;34m (Encriptada) "
echo -e $barra
unset selection
while [[ ${selection} != @([0-7]) ]]; do
echo -ne "\033[1;37mEscoje: " && read selection
tput cuu1 && tput dl1
done
case ${selection} in
1)
arquivo_move=chumogh.val
arquivo_enc=chumogh.enc
coco=adm-cgh
echo "INGRESA TUS DIGITOS A GERERAR TU KEY"
echo -ne "\033[1;37mKEY: " && read gerar
 #>> chumogh.val
echo -e "\033[1;32mKEY GENERADA ES :\033[1;35m $(ofus $gerar) \033[1;32m DESEAS COLOCARLA " 
mm=$(ofus $gerar)
while [[ ${yesno} != @(s|S|y|Y|n|N) ]]; do
read -p "[S/N]: " yesno
tput cuu1 && tput dl1
done
if [[ ${yesno} = @(s|S|y|Y) ]]; then
mkdir /etc/adm-cgh 1>/dev/null 2>/dev/null
mkdir /etc/adm-ct 1>/dev/null 2>/dev/null
echo -e "\033[1;34m Tiempo de Uso del KEY "
echo -e "  Use s = segundos, m = minutos, h = horas e d = dias EX: 14s ."
read -p " INGRESA : " tempoin
tempo=$(echo "$tempoin" |sed 's/ //g')
echo $tempo","$gerar >> /etc/adm-ct/tm
echo "#!/bin/bash
sleep $tempo
removeonline(){
    [[ -d /var/www/html ]] && [[ -e /var/www/html/chumogh.val ]] && rm -rf /var/www/html/chumogh.val > /dev/null 2>&1
    [[ -e /var/www/chumogh.val ]] && rm -rf /var/www/chumogh.val > /dev/null 2>&1
subironline
}   
subironline(){
[ ! -d /var ] && mkdir /var
[ ! -d /var/www ] && mkdir /var/www
[ ! -d /var/www/html ] && mkdir /var/www/html
[ ! -e /var/www/html/index.html ] && touch /var/www/html/index.html
[ ! -e /var/www/index.html ] && touch /var/www/index.html
chmod -R 755 /var/www
cp /root/chumogh.val /var/www/chumogh.val
cp /root/chumogh.val /var/www/html/chumogh.val
service apache2 restart
}
#kk=$(ofus $mm)
sed -i /$(ofus $mm)/d /root/chumogh.val
sed -i /$tempo","$gerar/d /etc/adm-ct/tm
rm -rf /etc/adm-cgh/$(ofus $gerar).sh
removeonline
exit" > /etc/adm-cgh/$(ofus $gerar).sh
#echo $(ofus $gerar) >> $arquivo_enc
echo $gerar >> /root/chumogh.val
echo -e "\033[1;33m Keys Activas En El Sistema"
cat /root/chumogh.val
listbar
sleep 2s
removeonline
bash /etc/adm-cgh/$(ofus $gerar).sh &
gerar
fi
;;
2)
arquivo_move=russ.val
arquivo_enc=russ.enc
coco=adm-russ
echo "INGRESA TUS DIGITOS A GERERAR TU KEY"
echo -ne "\033[1;37mKEY: " && read gerar
 #>> chumogh.val
echo -e "\033[1;32mKEY GENERADA ES :\033[1;35m $(ofus $gerar) \033[1;32m DESEAS COLOCARLA " 
mm=$(ofus $gerar)
while [[ ${yesno} != @(s|S|y|Y|n|N) ]]; do
read -p "[S/N]: " yesno
tput cuu1 && tput dl1
done
if [[ ${yesno} = @(s|S|y|Y) ]]; then
mkdir /etc/adm-russ 1>/dev/null 2>/dev/null
mkdir /etc/adm-tm 1>/dev/null 2>/dev/null
echo -e "\033[1;34m Tiempo de Uso del KEY "
echo -e "  Use s = segundos, m = minutos, h = horas e d = dias EX: 14s ."
read -p " INGRESA : " tempoin
tempo=$(echo "$tempoin" |sed 's/ //g')
echo $tempo","$gerar >> /etc/adm-ct/tmr
echo "#!/bin/bash
sleep $tempo
removeonline(){
    [[ -d /var/www/html ]] && [[ -e /var/www/html/russ.val ]] && rm -rf /var/www/html/russ.val > /dev/null 2>&1
    [[ -e /var/www/russ.val ]] && rm -rf /var/www/russ.val > /dev/null 2>&1
subironline
}   
subironline(){
[ ! -d /var ] && mkdir /var
[ ! -d /var/www ] && mkdir /var/www
[ ! -d /var/www/html ] && mkdir /var/www/html
[ ! -e /var/www/html/index.html ] && touch /var/www/html/index.html
[ ! -e /var/www/index.html ] && touch /var/www/index.html
chmod -R 755 /var/www
cp /root/russ.val /var/www/russ.val
cp /root/russ.val /var/www/html/russ.val
service apache2 restart
}
sed -i /$(ofus $mm)/d /root/russ.val
sed -i /$tempo","$gerar/d /etc/adm-ct/tmr
rm -rf /etc/adm-russ/$(ofus $gerar).sh
removeonline
exit" > /etc/adm-russ/$(ofus $gerar).sh
#echo $(ofus $gerar) >> $arquivo_enc
echo $gerar >> /root/russ.val
echo -e "\033[1;33m Keys Activas En el Sistema"
cat /root/russ.val
listbarr
sleep 2s
removeonline
bash /etc/adm-russ/$(ofus $gerar).sh &
gerar
fi
;;
3)
clear
figlet -p -f slant < /root/name
echo -e "\033[1;37m      【     ★ ChumoGH - ADM 2020 ★     】\033[0m"
echo -e "[\033[1;31m-\033[1;33m]\033[1;30m =======================================\033[1;33m"
echo -e "\033[1;37m ∆ Linux Dist:	$distribution › Version: $os_version\033[0m"
echo -e "[\033[1;31m-\033[1;33m]\033[1;30m =======================================\033[1;33m"
echo -e "\033[1;37m - Edicion Manual de Keys -  \033[0m"
echo -e "[\033[1;31m-\033[1;33m]\033[1;31m #######################################\033[1;33m"
echo -e "\033[1;37m Para Salir Ctrl + C o 0 Para Regresar\033[1;33m"
echo -e " \033[1;31m[ !!! ]\033[1;33m BORRA AQUI TU KEY   \033[1;31m\033[1;33m"
echo -e "${cor[1]} ▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪ ${cor[0]}"
echo -e " \033[1;31mLuego de Editar tus KEYS Presiona Ctrl + O y Enter \033[1;33m \033[1;31m\033[1;33m"
echo -e " \033[1;31m          Por Ultimo Ctrl + X  \033[1;33m \033[1;31m\033[1;33m"
echo -ne "\033[1;37m"
read -p " Presiona Enter para Continuar "
arquivo_move=chumogh.val
arquivo_enc=chumogh.enc
echo -e "\033[1;34m Keys Activas En Linea"
nano $arquivo_move
listbar
removeonline
gerar
;;
4)figlet -p -f slant < /root/name
echo -e "\033[1;37m      【     ★ ChumoGH - ADM 2020 ★     】\033[0m"
echo -e "[\033[1;31m-\033[1;33m]\033[1;30m =======================================\033[1;33m"
echo -e "\033[1;37m ∆ Linux Dist:	$distribution › Version: $os_version\033[0m"
echo -e "[\033[1;31m-\033[1;33m]\033[1;30m =======================================\033[1;33m"
echo -e "\033[1;37m - Edicion Manual de Keys -  \033[0m"
echo -e "[\033[1;31m-\033[1;33m]\033[1;31m #######################################\033[1;33m"
echo -e "\033[1;37m Para Salir Ctrl + C o 0 Para Regresar\033[1;33m"
echo -e " \033[1;31m[ !!! ]\033[1;33m BORRA AQUI TU KEY   \033[1;31m\033[1;33m"
echo -e "${cor[1]} ▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪ ${cor[0]}"
echo -e " \033[1;31mLuego de Editar tus KEYS Presiona Ctrl + O y Enter \033[1;33m \033[1;31m\033[1;33m"
echo -e " \033[1;31m          Por Ultimo Ctrl + X  \033[1;33m \033[1;31m\033[1;33m"
echo -ne "\033[1;37m"
read -p " Presiona Enter para Continuar "
arquivo_move=russ.val
arquivo_enc=russ.enc
echo -e "\033[1;34m Keys Activas En Linea"
nano $arquivo_move
listbar 
removeonline
gerar
;;
5)
    clear
    echo -e "\033[1;32m [0] > Regresar / Salir"
    echo -e "\033[1;32m [1] > Retirar KEY EN ADM CHUMOGH"
    echo -e "\033[1;32m [2] > Retirar KEY EN ADM RUSS"
    echo -e $barra
    unset sf
    while [[ ${sf} != @([0-2]) ]]; do
    echo -ne "\033[1;37mEscoje: " && read sf
    tput cuu1 && tput dl1
    done
    case ${sf} in
    1)
    figlet -p -f slant < /root/name
    echo -e "\033[1;37m      【     ★ ChumoGH - ADM 2020 ★     】\033[0m"
    echo -e "[\033[1;31m-\033[1;33m]\033[1;30m =======================================\033[1;33m"
    echo -e "\033[1;37m ∆ Linux Dist:	$distribution › Version: $os_version\033[0m"
    echo -e "[\033[1;31m-\033[1;33m]\033[1;30m =======================================\033[1;33m"
    echo -e "\033[1;37m -  Keys de CHUMOGH ADM -  \033[0m"
    echo -e "[\033[1;31m-\033[1;33m]\033[1;31m #######################################\033[1;33m"
    echo -e "\033[1;37m Para Salir Ctrl + C o 0 Para Regresar\033[1;33m"
    rm -f chumogh.*
    rm -rf /etc/adm-cgh/*
    #rm -f  /etc/adm-tm
    rm -f /etc/adm-ct/tm
    echo " Presiona Enter para Continuar"
    read -p " "
    gerar
    ;;
    2)
    figlet -p -f slant < /root/name
    echo -e "\033[1;37m      【     ★ RUSS - ADM 2020 ★     】\033[0m"
    echo -e "[\033[1;31m-\033[1;33m]\033[1;30m =======================================\033[1;33m"
    echo -e "\033[1;37m ∆ Linux Dist:	$distribution › Version: $os_version\033[0m"
    echo -e "[\033[1;31m-\033[1;33m]\033[1;30m =======================================\033[1;33m"
    echo -e "\033[1;37m -  Keys de RUSS ADM -  \033[0m"
    echo -e "[\033[1;31m-\033[1;33m]\033[1;31m #######################################\033[1;33m"
    echo -e "\033[1;37m Para Salir Ctrl + C o 0 Para Regresar\033[1;33m"
    echo -e "${cor[1]} ▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪ ${cor[0]}"
    rm -f russ.*
    rm -rf /etc/adm-russ/*
    #rm -f  /etc/adm-tmr
    rm -f /etc/adm-ct/tmr
    echo " Presiona Enter para Continuar"
    read -p " "
    gerar
    ;;
    0)cd $HOME && gerar;;
    esac
;;
6)
figlet -p -f slant < /root/name
echo -e "\033[1;37m      【     ★ ChumoGH - ADM 2020 ★     】\033[0m"
echo -e "[\033[1;31m-\033[1;33m]\033[1;30m =======================================\033[1;33m"
echo -e "\033[1;37m ∆ Linux Dist:	$distribution › Version: $os_version\033[0m"
echo -e "[\033[1;31m-\033[1;33m]\033[1;30m =======================================\033[1;33m"
echo -e "\033[1;37m -  Keys de CHUMOGH ADM -  \033[0m"
echo -e "[\033[1;31m-\033[1;33m]\033[1;31m #######################################\033[1;33m"
echo -e "\033[1;37m Para Salir Ctrl + C o 0 Para Regresar\033[1;33m"
echo -e "${cor[1]} ▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪ ${cor[0]}"
echo -e " \033[1;31m  Lista de Keys GENERADAS \033[1;33m \033[1;31m\033[1;33m"
#echo -e "${cor[1]}▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪ ${cor[0]}"
echo -e "\033[1;37m            KEYS de USO en LINEA"
echo -e "${cor[1]}▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪ ${cor[0]}"
echo -ne "\033[1;37m"
for testus in $(ls /etc/adm-cgh |sort |sed 's/.sh//g')
do
echo "$testus" 
done
echo -e "\033[1;35m            KEYS ORIGINAL EN SISTEMA"
echo -e "${cor[1]}▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪ ${cor[0]}"
echo -ne "\033[1;35m"
#cat chumogh.val
i=0
#i=$(( $i + 1 ))
xm=$(cat /etc/adm-ct/tm | wc -l)
#for((i=1; i=xm; i++)); do
#echo -e "\033[1;34mKey\033[1;36m$i: \033[1;34m$ky \033[1;35mCaduca en: \033[1;34m$tim"
#done
    while IFS=,  read -r tim ky
    do
        echo -e "\033[1;34mKey: \033[1;34m$ky \033[1;35mDIED:\033[1;34m$tim"
    done < /etc/adm-ct/tm
#done
echo -e "${cor[1]}▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪ ${cor[0]}"
read -p " Presiona Enter para Continuar "
gerar
;;
7)
figlet -p -f slant < /root/name
echo -e "\033[1;37m      【     ★ RUSS - ADM 2020 ★     】\033[0m"
echo -e "[\033[1;31m-\033[1;33m]\033[1;30m =======================================\033[1;33m"
echo -e "\033[1;37m ∆ Linux Dist:	$distribution › Version: $os_version\033[0m"
echo -e "[\033[1;31m-\033[1;33m]\033[1;30m =======================================\033[1;33m"
echo -e "\033[1;37m -  Keys de RUSS ADM -  \033[0m"
echo -e "[\033[1;31m-\033[1;33m]\033[1;31m #######################################\033[1;33m"
echo -e "\033[1;37m Para Salir Ctrl + C o 0 Para Regresar\033[1;33m"
echo -e "${cor[1]} ▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪ ${cor[0]}"
echo -e " \033[1;31m  Lista de Keys GENERADAS \033[1;33m \033[1;31m\033[1;33m"
#echo -e "${cor[1]} ▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪ ${cor[0]}"
echo -e "\033[1;34m            KEYS de USO en LINEA"
echo -e "${cor[1]}▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪ ${cor[0]}"
echo -ne "\033[1;37m"
for testus in $(ls /etc/adm-russ |sort |sed 's/.sh//g')
do
echo "$testus"
done
echo -e "\033[1;35m            KEYS ORIGINAL EN SISTEMA"
echo -e "${cor[1]} ▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪ ${cor[0]}"
echo -ne "\033[1;35m"
i=0
#i=$(( $i + 1 ))
xm=$(cat /etc/adm-ct/tmr | wc -l)
#for((i=1; i=xm; i++)); do
unset tim ky
#echo -e "\033[1;34mKey\033[1;36m$i: \033[1;34m$ky \033[1;35mCaduca en: \033[1;34m$tim"
#done
    while IFS=,  read -r tim ky
    do
        echo -e "\033[1;34mKey: \033[1;34m$ky \033[1;35mDIED:\033[1;34m$tim"
    done < /etc/adm-ct/tmr
echo -e "${cor[1]} ▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪ ${cor[0]}"
read -p " Presiona Enter para Continuar "
gerar
;;
0)cd $HOME && exit;;
esac
