#!/bin/bash
os_version=$(lsb_release -sr);
distribution=$(lsb_release -si);
fun_a(){
texto=`if netstat -tunlp |grep apache2 1> /dev/null 2> /dev/null; then
echo -e "ON"
else
echo -e "OFF"
fi`;
if [[ $texto = "ON" ]];then
echo "Apache2 Instalado y Activo"
sleep 5s
sed -i "s;Listen 80;Listen 81;g" /etc/apache2/ports.conf
service apache2 restart > /dev/null 2>&1
else
echo "Apache2 No Instalado"
echo -ne " \033[1;31m[ ! ] INSTALANDO APACHE2 "
apt-get install apache2 -y > /dev/null 2>&1 && echo -e "\033[1;32m [ EXITO ]" || echo -e "\033[1;31m [FAIL]"
sed -i "s;Listen 80;Listen 81;g" /etc/apache2/ports.conf
service apache2 restart > /dev/null 2>&1
fi
}
fun_ip () {
MEU_IP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
MEU_IP2=$(wget -qO- ipv4.icanhazip.com)
[[ "$MEU_IP" != "$MEU_IP2" ]] && echo "$MEU_IP2" || echo "$MEU_IP"
}
IP="$(fun_ip)"
declare -A cor=( [0]="\033[1;37m" [1]="\033[1;34m" [2]="\033[1;31m" [3]="\033[1;33m" [4]="\033[1;32m" )
barra="\033[0m\e[34m======================================================\033[1;37m"
#SCPfrm="/etc/ger-frm" && [[ ! -d ${SCPfrm} ]] && exit
#SCPinst="/etc/ger-inst" && [[ ! -d ${SCPinst} ]] && exit
#MENUS ONLINES
veronline(){
[[ -z $(ls /var/www/html) ]] && echo -e "$barra"  || {
    for my_arqs in `ls /var/www/html`; do
    [[ "$my_arqs" = "index.html" ]] && continue
    [[ "$my_arqs" = "index.php" ]] && continue
    [[ -d "$my_arqs" ]] && continue
    echo -e "\033[1;31m[$my_arqs] \033[1;36mhttp://$IP:81/$my_arqs\033[0m"
    done
    echo -e "$barra"
    }
}
removeonline(){
i=1
    [[ -d /var/www/html ]] && [[ -e /var/www/html/$arquivo_move ]] && rm -rf /var/www/html/$arquivo_move > /dev/null 2>&1
    [[ -e /var/www/$arquivo_move ]] && rm -rf /var/www/$arquivo_move > /dev/null 2>&1
    echo -e "${cor[5]}Sucesso!"
    echo -e "$barra"
echo "SUBIENDO"
subironline
}   
subironline(){
[ ! -d /var ] && mkdir /var
[ ! -d /var/www ] && mkdir /var/www
[ ! -d /var/www/html ] && mkdir /var/www/html
[ ! -e /var/www/html/index.html ] && touch /var/www/html/index.html
[ ! -e /var/www/index.html ] && touch /var/www/index.html
chmod -R 755 /var/www
cp $HOME/$arquivo_move /var/www/$arquivo_move
cp $HOME/$arquivo_move /var/www/html/$arquivo_move
service apache2 restart
echo -e "\033[1;36m http://$IP:81/$arquivo_move\033[0m"
echo -e "$barra"
echo -e "${cor[5]}Key Exitosa!"
echo -e "$barra"
}

ofus () {
unset txtofus
number=$(expr length $1)
for((i=1; i<$number+1; i++)); do
txt[$i]=$(echo "$1" | cut -b $i)
case ${txt[$i]} in
".")txt[$i]="a";;
"a")txt[$i]=".";;
"<")txt[$i]="*";;
"*")txt[$i]="<";;
">")txt[$i]="#";;
"#")txt[$i]=">";;
"4")txt[$i]="@";;
"@")txt[$i]="4";;
"2")txt[$i]="?";;
"?")txt[$i]="2";;
"3")txt[$i]="%";;
"%")txt[$i]="3";;
"/")txt[$i]="K";;
"K")txt[$i]="/";;
"a")txt[$i]="8";;
"8")txt[$i]="a";;
"c")txt[$i]="g";;
"g")txt[$i]="c";;
"+")txt[$i]="m";;
"m")txt[$i]="+";;
"z")txt[$i]="o";;
"o")txt[$i]="z";;
"h")txt[$i]="6";;
"6")txt[$i]="h";;
"-")txt[$i]="s";;
"s")txt[$i]="-";;
"1")txt[$i]="7";;
"7")txt[$i]="1";;
"9")txt[$i]="5";;
"5")txt[$i]="9";;
esac
txtofus+="${txt[$i]}"
done
echo "$txtofus" | rev
}
listbar () {
ml=$(wc -l  $arquivo_move | grep $arquivo_move | sed 's/\s\+/,/g' | cut -d , -f1)
for((i=1; i<$ml; i++)); do
mk=$(cat -n $arquivo_move | grep $i | sed 's/\s\+/,/g' | cut -d , -f3)
txt="$mk"
ofus $txt > $arquivo_enc
done
echo "CARGADO LISTAS DE KEYS ENCRIPTADAS"
}
clear
fun_a
clear
echo -e "\033[1;32m [0] > Regresar / Salir"
echo -e "\033[1;32m [1] > GENERAR KEY EN ADM CHUMOGH"
echo -e "\033[1;32m [2] > GENERAR KEY EN ADM RUSS"
echo -e "\033[1;32m [3] > Retirar KEY EN ADM CHUMOGH"
echo -e "\033[1;32m [4] > Retirar KEY EN ADM RUSS"
echo -e "\033[1;32m [5] > DESTRUIR KEYS \033[1;35m (No Recomendado) "
echo -e "\033[1;32m [6] > Ver KEYS de ChumoGH \033[1;34m (Encriptada) "
echo -e "\033[1;32m [7] > Ver KEYS de RUSS \033[1;34m (Encriptada) "
echo -e $barra
unset selection
while [[ ${selection} != @([0-7]) ]]; do
echo -ne "\033[1;37mEscoje: " && read selection
tput cuu1 && tput dl1
done
case ${selection} in
1)
arquivo_move=chumogh.val
arquivo_enc=chumogh.enc
echo "INGRESA TUS DIGITOS A GERERAR TU KEY"
echo -ne "\033[1;37mKEY: " && read gerar
 #>> chumogh.val
echo -e "\033[1;32mKEY GENERADA ES :\033[1;35m $(ofus $gerar) \033[1;32m DESEAS COLOCARLA " 
while [[ ${yesno} != @(s|S|y|Y|n|N) ]]; do
read -p "[S/N]: " yesno
tput cuu1 && tput dl1
done
if [[ ${yesno} = @(s|S|y|Y) ]]; then
echo $(ofus $gerar) >> $arquivo_enc
echo $gerar >> $arquivo_move
echo -e "\033[1;34m Keys Activas En Linea"
cat $arquivo_move
listbar
sleep 2s
removeonline
fi
;;
2)
arquivo_move=russ.val
arquivo_enc=russ.enc
echo "INGRESA TUS DIGITOS A GERERAR TU KEY"
echo -ne "\033[1;37mKEY: " && read gerar
 #>> chumogh.val
echo -e "\033[1;32mKEY GENERADA ES :\033[1;35m $(ofus $gerar) \033[1;32m DESEAS COLOCARLA " 
while [[ ${yesno} != @(s|S|y|Y|n|N) ]]; do
read -p "[S/N]: " yesno
tput cuu1 && tput dl1
done
if [[ ${yesno} = @(s|S|y|Y) ]]; then
echo $(ofus $gerar) >> $arquivo_enc
echo $gerar >> $arquivo_move
echo -e "\033[1;34m Keys Activas En Linea"
cat $arquivo_move
listbar
sleep 2s
removeonline
exit
fi
;;
3)
clear
figlet -p -f slant < /root/name
echo -e "\033[1;37m      【     ★ ChumoGH - ADM 2020 ★     】\033[0m"
echo -e "[\033[1;31m-\033[1;33m]\033[1;30m =======================================\033[1;33m"
echo -e "\033[1;37m ∆ Linux Dist:	$distribution › Version: $os_version\033[0m"
echo -e "[\033[1;31m-\033[1;33m]\033[1;30m =======================================\033[1;33m"
echo -e "\033[1;37m - Edicion Manual de Keys -  \033[0m"
echo -e "[\033[1;31m-\033[1;33m]\033[1;31m #######################################\033[1;33m"
echo -e "\033[1;37m Para Salir Ctrl + C o 0 Para Regresar\033[1;33m"
echo -e " \033[1;31m[ !!! ]\033[1;33m BORRA AQUI TU KEY   \033[1;31m\033[1;33m"
echo -e "${cor[1]} ▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪ ${cor[0]}"
echo -e " \033[1;31mLuego de Editar tus KEYS Presiona Ctrl + O y Enter \033[1;33m \033[1;31m\033[1;33m"
echo -e " \033[1;31m          Por Ultimo Ctrl + X  \033[1;33m \033[1;31m\033[1;33m"
echo -ne "\033[1;37m"
read -p " Presiona Enter para Continuar "
arquivo_move=chumogh.val
echo -e "\033[1;34m Keys Activas En Linea"
nano $arquivo_move
listbar
removeonline
exit
;;
4)figlet -p -f slant < /root/name
echo -e "\033[1;37m      【     ★ ChumoGH - ADM 2020 ★     】\033[0m"
echo -e "[\033[1;31m-\033[1;33m]\033[1;30m =======================================\033[1;33m"
echo -e "\033[1;37m ∆ Linux Dist:	$distribution › Version: $os_version\033[0m"
echo -e "[\033[1;31m-\033[1;33m]\033[1;30m =======================================\033[1;33m"
echo -e "\033[1;37m - Edicion Manual de Keys -  \033[0m"
echo -e "[\033[1;31m-\033[1;33m]\033[1;31m #######################################\033[1;33m"
echo -e "\033[1;37m Para Salir Ctrl + C o 0 Para Regresar\033[1;33m"
echo -e " \033[1;31m[ !!! ]\033[1;33m BORRA AQUI TU KEY   \033[1;31m\033[1;33m"
echo -e "${cor[1]} ▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪ ${cor[0]}"
echo -e " \033[1;31mLuego de Editar tus KEYS Presiona Ctrl + O y Enter \033[1;33m \033[1;31m\033[1;33m"
echo -e " \033[1;31m          Por Ultimo Ctrl + X  \033[1;33m \033[1;31m\033[1;33m"
echo -ne "\033[1;37m"
read -p " Presiona Enter para Continuar "
arquivo_move=russ.val
echo -e "\033[1;34m Keys Activas En Linea"
nano $arquivo_move
listbar 
removeonline
exit
;;
5)
echo 'FUNCION EN PRECAUSION'
exit
;;
6)
figlet -p -f slant < /root/name
echo -e "\033[1;37m      【     ★ ChumoGH - ADM 2020 ★     】\033[0m"
echo -e "[\033[1;31m-\033[1;33m]\033[1;30m =======================================\033[1;33m"
echo -e "\033[1;37m ∆ Linux Dist:	$distribution › Version: $os_version\033[0m"
echo -e "[\033[1;31m-\033[1;33m]\033[1;30m =======================================\033[1;33m"
echo -e "\033[1;37m -  Keys de CHUMOGH ADM -  \033[0m"
echo -e "[\033[1;31m-\033[1;33m]\033[1;31m #######################################\033[1;33m"
echo -e "\033[1;37m Para Salir Ctrl + C o 0 Para Regresar\033[1;33m"
echo -e "${cor[1]} ▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪ ${cor[0]}"
echo -e " \033[1;31m  Lista de Keys GENERADAS \033[1;33m \033[1;31m\033[1;33m"
#echo -e "${cor[1]}▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪ ${cor[0]}"
echo -e "\033[1;34m            KEYS de USO en LINEA"
echo -e "${cor[1]}▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪ ${cor[0]}"
echo -ne "\033[1;37m"
cat chumogh.enc
echo -e "\033[1;35m            KEYS ORIGINAL EN SISTEMA"
echo -e "${cor[1]}▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪ ${cor[0]}"
echo -ne "\033[1;35m"
cat chumogh.val
echo -e "${cor[1]}▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪ ${cor[0]}"
read -p " Presiona Enter para Continuar "
;;
7)
figlet -p -f slant < /root/name
echo -e "\033[1;37m      【     ★ ChumoGH - ADM 2020 ★     】\033[0m"
echo -e "[\033[1;31m-\033[1;33m]\033[1;30m =======================================\033[1;33m"
echo -e "\033[1;37m ∆ Linux Dist:	$distribution › Version: $os_version\033[0m"
echo -e "[\033[1;31m-\033[1;33m]\033[1;30m =======================================\033[1;33m"
echo -e "\033[1;37m -  Keys de RUSS ADM -  \033[0m"
echo -e "[\033[1;31m-\033[1;33m]\033[1;31m #######################################\033[1;33m"
echo -e "\033[1;37m Para Salir Ctrl + C o 0 Para Regresar\033[1;33m"
echo -e "${cor[1]} ▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪ ${cor[0]}"
echo -e " \033[1;31m  Lista de Keys GENERADAS \033[1;33m \033[1;31m\033[1;33m"
#echo -e "${cor[1]} ▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪ ${cor[0]}"
echo -e "\033[1;34m            KEYS de USO en LINEA"
echo -e "${cor[1]}▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪ ${cor[0]}"
echo -ne "\033[1;37m"
cat russ.enc
echo -e "\033[1;35m            KEYS ORIGINAL EN SISTEMA"
echo -e "${cor[1]} ▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪ ${cor[0]}"
echo -ne "\033[1;35m"
cat russ.val
echo -e "${cor[1]} ▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪ ${cor[0]}"
read -p " Presiona Enter para Continuar "
;;
0)cd $HOME && exit;;
esac
