#!/bin/sh
#Autor: Henry Chumo 
#Alias : ChumoGH
opti=$(cat /bin/ejecutar/val)
if [ "$opti" = "0" ]; then
rm -f /bin/ejecutar/automatizar.sh
echo "echo 3 > /proc/sys/vm/drop_caches" >> /bin/ejecutar/automatizar.sh
echo "sudo sync"  >> /bin/ejecutar/automatizar.sh
echo "sudo sysctl -w vm.drop_caches=3" >> /bin/ejecutar/automatizar.sh
echo "sysctl -w vm.drop_caches=3 > /dev/null 2>&1" >> /bin/ejecutar/automatizar.sh
echo "rm -rf /tmp/*" >> /bin/ejecutar/automatizar.sh
echo 'echo "Memoria Liberada"' >> /bin/ejecutar/automatizar.sh
echo "tiempo=$(hwclock)" >> /bin/ejecutar/automatizar.sh
echo "echo $tiempo >> /root/dropcache" >> /bin/ejecutar/automatizar.sh
echo "* */5 * * *	root 	sh /bin/ejecutar/automatizar.sh" >> /etc/crontab
_opti="\033[1;31m${txt[11]}"
else
_opti="\033[1;32m${txt[10]}"
fi

