#!/bin/bash
source cabecalho
mt=$(free -h | grep Mem | sed 's/\s\+/,/g' | cut -d , -f2)
mf=$(free -h | grep Mem | sed 's/\s\+/,/g' | cut -d , -f4)
if [ "$(find . -type f -iname "*.block" | wc -l)" > 0 ]; then
ul="\033[1;33m( \033[1;31m$(find . -type f -iname "*.block" | wc -l) \033[1;32mLOCKED \033[1;33m)"
else
ul="\033[1;33m( \033[1;32mALL UNLOCK \033[1;33m)"
fi
usoo=$(grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage "%"}')
CPU=$(echo $usoo "%" | awk '{printf("%d\n",$1 + 0.5)}')
msg -bar #echo -e "${cor[1]} ▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪ ${cor[0]}"
echo -e "${cor[2]} 🦖 ${cor[5]} ${txt[14]} ${txt[356]}"
echo -e "\033[1;34m ▸ M Total: \033[1;32m$mt\033[1;34m ▸ M Libre: \033[1;32m$mf\033[1;34m ▸ Uso CPU:\033[1;32m $_usop "
msg -bar #echo -e "${cor[1]} ▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪ ${cor[0]}"
echo -e "${cor[2]} [0] >${cor[4]} ${txt[13]}"
echo -e "${cor[2]} [1] >${cor[3]} ${txt[353]}" #  ${cor[2]} [-] >${cor[3]} - "
echo -e "${cor[2]} [2] >${cor[3]} ${txt[15]}" #   ${cor[2]}   [-] >${cor[3]} - "
echo -e "${cor[2]} [3] >${cor[3]} ${txt[16]}" #    ${cor[2]}       [-] >${cor[3]} -"
echo -e "${cor[2]} [4] >${cor[3]} ${txt[17]}" #   ${cor[2]}     [-] >${cor[3]} - "
echo -e "${cor[2]} [5] >${cor[3]} ${txt[18]}" #  ${cor[2]} [-] >${cor[3]} - "
echo -e "${cor[2]} [6] >${cor[3]} ${txt[19]}" #  ${cor[2]} [-] >${cor[3]} - "
echo -e "${cor[2]} [7] >${cor[3]} ${txt[87]}" #   ${cor[2]}        [-] >${cor[3]} - "
echo -e "${cor[2]} [8] >${cor[3]} ${txt[234]}" #  ${cor[2]}     [-] >${cor[3]} - "
echo -e "${cor[2]} [9] >${cor[3]} ${txt[288]}"
echo -e "${cor[2]} [10] >${cor[3]} Bloquear Usuario Fijo $ul"
echo -e "${cor[2]} [11] >${cor[3]} BACKUP USUARIOS \033[1;33m( #OFFICIAL )"

if [ -e /etc/cgh/modulo/limiter ]; then
echo -e "\033[1;31m \033[1;36m \033[1;32m(ON)\033[1;36m ${txt[354]} $limiter_on"
else
echo -e "\033[1;31m\033[1;36m \033[1;31m(OFF) \033[1;36m ${txt[355]} $limiter_on\033[0m"
fi
#echo -e "${cor[2]} [10] >${cor[3]} ${txt[254]} $limiter_on ✈ "
msg -bar #echo -e "${cor[1]} ▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪ ${cor[0]}"
