#!/bin/bash
dir_user="/userDIR"
dir="/etc/adm-lite"
bc="$HOME/backup"
echo -e "\033[1;33mBackup\033[1;30m
1) Crear respaldo de usuarios
2) Restaurar usuarios de un backup"
read -p "opcion: " option
function backup_de_usuarios(){
clear
[[ -d $bc ]] && rm $bc
echo -e "\033[1;37mHaciendo Backup de Usuarios...\033[0m"
for user in `awk -F : '$3 > 900 { print $1 }' /etc/passwd |grep -v "nobody" |grep -vi polkitd |grep -vi systemd-[a-z] |grep -vi systemd-[0-9]`
do
if [ -e $dir$dir_user/$user ]
then
pass=$(cat $dir$dir_user/$user | grep "senha" | awk '{print $2}')
else
echo -e "\033[1;31mNo fue posible obtener la contraseña del usuario\033[1;37m ($user)"
read -p "Introduzca la contraseña manualmente o pulse ENTER: " pass
fi
if [ -e $dir$dir_user/$user ]
then
limite=$(cat $dir$dir_user/$user | grep "limite" | awk '{print $2}')

echo "$user:$pass:$limite" >> $bc
echo -e "\033[1;37mUser $user Backup [\033[1;31mOK\033[1;37m]\033[0m"
else
echo "$user:$pass" >>  $bc
echo -e "\033[1;37mUser $user Backup [\033[1;31mOK\033[1;37m]\033[0m"
fi
done
echo " "
echo -e "\033[1;31mBackup Completado !!!\033[0m"
echo " "
echo -e "\033[1;37mLa informacion de los usuarios se encuentra en el archivo \033[1;31m $bc \033[1;37m
Guardelo para una futura restauracion\033[0m"
}
function restaurar_usuarios(){
cd $HOME
echo -n "INGRESE LINK DEL POSTER DE BACKUP" 
read url1
wget -O recovey $url1 -o /dev/null 2>&1
#echo -n "Escriba el directorio del archivo Backup: "
echo -e "\033[1;37mRestaurando Usuarios...\033[0m"
[[ -d $HOME/recovery ]] && arq="$HOME/recovery" || unset arq
for user in `cat $arq`
do
usuario=$(echo "$user" |awk -F : '{print $1}')
senha=$(echo "$user" |awk -F : '{print $2}')
if cat /etc/passwd |grep $usuario: 1> /dev/null 2>/dev/null
then
echo " " > /dev/null
else
echo "$user" |cut -d: -f3 1> /dev/null 2>/dev/null
  if [ $? = 0 ]
  then
  limite=$(echo "$user" |awk -F : '{print $3}')
  useradd -M -s /bin/false $usuario
  (echo $senha ; echo $senha) | passwd $usuario > /dev/null 2> /dev/null
  limit $usuario $limite 1> /dev/null 2> /dev/null
  echo "senha: $senha$senha" > $dir$dir_user/$user
  echo "limite: $limite" >> $dir$dir_user/$user
  else
  useradd -M -s /bin/false $usuario
  (echo $senha ; echo $senha) | passwd $usuario > /dev/null 2> /dev/null
  echo "senha: $senha" > $dir$dir_user/$user
  fi
  echo -e "\033[1;37mUsuario: \033[1;31m$usuario \033[1;37mBackup: [\033[1;31mOk\033[1;37m]\033[0m"
fi
done
}
if [ $option -eq 1 ]; then
backup_de_usuarios
fi

if [ $option -eq 2 ]; then
restaurar_usuarios
fi
